name: Pixi Contact Form Plugin Assets Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Plugin Assets
        run: |
          # Customize this script to deploy your assets
          # For example, use SVN to upload assets to WordPress.org
          svn co https://plugins.svn.wordpress.org/pixi-contact-form-for-elementor/ /tmp/pixi-contact-form-for-elementor
          cp -r assets/* /tmp/pixi-contact-form-for-elementor/assets/
          cd /tmp/pixi-contact-form-for-elementor
          svn add assets/
          svn commit -m "Deploy assets for version 1.0.1"
          svn up
          rm -rf /tmp/pixi-contact-form-for-elementor
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
